import context from "./context"
import { errors, validators } from "com"

const { validateId } = validators

/**
 * Generates a summary from the topics discussed in a conversation.
 * 
 * @param {string} conversationId The conversation id.
 * 
 * @returns {Promise<string>} The summary text generated by the API.
 * 
 * @throws {TypeError} On non-string conversation id
 * @throws {ContentError} On conversation id length not equal to 24 characters
 */

export default function generateSummary(conversationId) {
    validateId(conversationId, 'conversation id')

    return (async () => {
        const res = await fetch(`${import.meta.env.VITE_API_URL}/users/conversations/${conversationId}/generateSummary`, {
            method: 'GET',
            headers: {
                'Authorization': `Bearer ${context.token}`
            }
        })

        if (res.status === 201)
            return res.text()

        const { type, message } = await res.json()

        const clazz = errors[type]

        throw new clazz(message)
    })()
}