module.exports = {
    authenticateUser: require('./authenticateUser'),
    createPost: require('./createPost'),
    deletePost: require('./deletePost'),
    registerUser: require('./registerUser'),
    retrieveOnSalePosts: require('./retrieveOnSalePosts'), 
    retrievePost: require('./retrievePost'),
    retrievePosts: require('./retrievePosts'),
    retrieveUser: require('./retrieveUser'),    
    retrieveSavePosts: require('./retrieveSavePosts'),
    retrieveUsersPosts: require('./retrieveUsersPosts'),
    toggleLockPost: require('./toggleLockPost'),
    toggleLikePost: require('./toggleLikePost'),
    toggleSavePost: require('./toggleSavePost'),
    updateBuyPost: require('./updateBuyPost'),
    updatePost: require('./updatePost'),
    updatePriceToPost: require('./updatePriceToPost'),
    updateUserAvatar: require('./updateUserAvatar'),
    updateUserMode: require('./updateUserMode'),
    updateUserPassword: require('./updateUserPassword')
}