module.exports = {
  authenticateUserHandler: require('./authenticateUserHandler'),
  createPostHandler: require('./createPostHandler'),
  deletePostHandler: require('./deletePostHandler'),
  registerUserHandler: require('./registerUserHandler'),
  retrieveUserHandler: require('./retrieveUserHandler'),
  retrievePostsHandler: require('./retrievePostsHandler'),
  retrievePostHandler: require('./retrievePostHandler'),
  toggleFavouritePostHandler: require('./toggleFavouritePostHandler'),
  toggleLikePostHandler: require('./toggleLikePostHandler'),
  updateUserAvatarHandler: require('./updateUserAvatarHandler'),
  updateUserPasswordHandler: require('./updateUserPasswordHandler'),
  updatePostHandler: require('./updatePostHandler'),
  addCommentHandler: require('./addCommentHandler'),
  deleteCommentHandler: require('./deleteCommentHandler'),
};
