module.exports = {
    helloApiHandler: require('./helloApiHandler'),
    registerUserHandler: require('./registerUserHandler'),
    authenticateUserHandler: require('./authenticateUserHandler'),
    getLoggedUserHandler: require('./getLoggedUserHandler'),
    updateCharacterHandler: require('./updateCharacterHandler'),
    updateUserEmailHandler: require('./updateUserEmailHandler'),
    updateUsernameHandler: require('./updateUsernameHandler'),
    updateUserPasswordHandler: require('./updateUserPasswordHandler'),
    deleteAccountHandler: require('./deleteAccountHandler'),
    createNewMissionHandler: require('./createNewMissionHandler'),
    retriveMissionsHandler: require('./retriveMissionsHandler'),
    retriveMissionHandler: require('./retriveMissionHandler'),
    updateMissionHandler: require('./updateMissionHandler'),
    deleteMissionHandler: require('./deleteMissionHandler'),
    updateUsernameHandler: require('./updateUsernameHandler'),
    updateUserEmailHandler: require('./updateUserEmailHandler'),
    updateUserPasswordHandler: require('./updateUserPasswordHandler'),
    createNewCharacterHandler: require('./createNewCharacterHandler'),
    getUserCharacterHandler: require('./getUserCharacterHandler'),
    registerCompletedMissionHandler: require('./registerCompletedMissionHandler'),
    retriveAdminMissionsHandler: require('./retriveAdminMissionsHandler')
}