module.exports = {
    registerEmployee: require('./registerEmployee'),
    authenticateEmployee: require('./authenticateEmployee'),
    retrieveEmployeeLogged: require('./retrieveEmployeeLogged'),
    retrieveEmployeePayrollData: require('./retrieveEmployeePayrollData'),
    retrieveEmployeePayrollToBePaid: require('./retrieveEmployeePayrollToBePaid'),
    createEmployeePayrollMonth: require('./createEmployeePayrollMonth'),
    retrieveEmployee: require('./retrieveEmployee'),
    updateEmployee: require('./updateEmployee'),
    updateEmployeeAvatar: require('./updateEmployeeAvatar'),
    updateEmployeePassword: require('./updateEmployeePassword'),
    updateEmployeeBankAccountNumber: require('./updateEmployeeBankAccountNumber'),
    updateEmployeeAddress: require('./updateEmployeeAddress'),
    searchEmployees: require('./searchEmployees'),
    retrievePayrollMonth: require('./retrievePayrollMonth'),
    retrieveEmployeesBySalaryLevel: require('./retrieveEmployeesBySalaryLevel'),
    retrievePayrollAnnualAggregate: require('./retrievePayrollAnnualAggregate'),
    retrievePayrollsMonthToBePaid: require('./retrievePayrollsMonthToBePaid'),
    updatePayrollStatusToPaid: require('./updatePayrollStatusToPaid'),
    getTreeChart: require('./getTreeChart'),
    resetPassword: require('./resetPassword'),
    deletePayrollMonth: require('./deletePayrollMonth'),

}
