module.exports = {
    registerUser: require('./registerUser'),
    authenticateUserEmail: require('./authenticateUserEmail'),
    authenticateUser: require('./authenticateUser'),
    retrieveUser: require('./retrieveUser'),
    createEvent: require('./createEvent'),
    createEventReview: require('./createEventReview'),
    // updateUserPassword: require('./updateUserPassword'),
    // updateUserAvatar: require('./updateUserAvatar'),
    // deleteEvent: require('./deleteEvent'),
    // updateEvent: require('./updateEvent'),
    // updateUserEmail: require('./updateUserEmail'),
    // toggleLikeEvent: require('./toggleLikeEvent'),
    // toggleFavEvent: require('./toggleFavEvent'),
    // retrieveEvent: require('./retrieveEvent'),
    // retrieveEvents: require('./retrieveEvents'),
    // retrieveLikedEvents: require('./retrieveLikedEvents'),
    // retrieveFavEvents: require('./retrieveFavEvents'),
    // addCommentToEvent: require('./addCommentToEvent'),
    // removeCommentFromEvent: require('./removeCommentFromEvent')
}