module.exports = {
    helloApiHandler: require('./helloApiHandler'),
    authenticateAdminHandler: require('./administrator/authenticateAdminHandler'),
    registerAdminHandler: require('./administrator/registerAdminHandler'),
    updateAdminEmailHandler: require('./administrator/updateAdminEmailHandler'),
    updateAdminPasswordHandler: require('./administrator/updateAdminPasswordHandler'),
    deleteAdminHandler: require('./administrator/deleteAdminHandler'),
    createUpdateHandler: require('./update/createUpdateHandler'),
    modifyUpdateHandler: require('./update/modifyUpdateHandler'),
    deleteUpdateHandler: require('./update/deleteUpdateHandler'),
    toggleUpdateVisibilityHandler: require('./update/toggleUpdateVisibilityHandler'),
    createEventHandler: require('./event/createEventHandler'),
    modifyEventHandler: require('./event/modifyEventHandler'),
    deleteEventHandler: require('./event/deleteEventHandler'),
    toggleEventVisibilityHandler: require('./event/toggleEventVisibilityHandler'),
    createLyricPostHandler: require('./lyricPost/createLyricPostHandler'),
    modifyLyricPostHandler: require('./lyricPost/modifyLyricPostHandler'),
    deleteLyricPostHandler: require('./lyricPost/deleteLyricPostHandler'),
    toggleLyricPostVisibilityHandler: require('./lyricPost/toggleLyricPostVisibilityHandler'),
    createMessageHandler: require('./message/createMessageHandler'),
    readMessageHandler: require('./message/readMessageHandler'),
    deleteMessageHandler: require('./message/deleteMessageHandler'),
    toggleMessageReadHandler: require('./message/toggleMessageReadHandler'),
    seeUpdateHandler: require('./update/seeUpdateHandler'),
    seeEventHandler: require('./event/seeEventHandler'),
    seeLyricPostHandler: require('./lyricPost/seeLyricPostHandler')
  }