module.exports = {
    createLevel: require('./levels/createLevel'),
    retrieveLevel: require('./levels/retrieveLevel'),
    retrieveLevels: require('./levels/retrieveLevels'),
    registerUser: require('./users/registerUser'),
    authenticateUser: require('./users/authenticateUser'),
    retrieveUser: require('./users/retrieveUser'),
    retrieveUserLogged: require('./users/retrieveUserLogged'),
    updateColor: require('./users/updateColor'),
    updateAvatar: require('./users/updateAvatar'),
    toggleLike: require('./levels/toggleLike'),
    checkRecoveryAnswer: require('./users/checkRecoveryAnswer'),
    recoverPassword: require('./users/recoverPassword'),
    retrieveRandomRecoveryQuestion: require('./users/retrieveRandomRecoveryQuestion'),
    updatePassword: require('./users/updatePassword'),
    toggleFollow: require('./users/toggleFollow'),
    retrieveLevelsByFollowed: require('./levels/retrieveLevelsByFollowed'),
    retrieveLevelsByAuthor: require('./levels/retrieveLevelsByAuthor'),
    toggleSave: require('./levels/toggleSave'),
    retrieveLevelsSaved: require('./levels/retrieveLevelsSaved'),
    retrieveCompleteAchievements: require('./achievements/retrieveCompleteAchievements'),
    updateCreateAchievements: require('./achievements/updateCreateAchievements'),
    updateGameAchievements: require('./achievements/updateGameAchievements'),
    updateSocialAchievements: require('./achievements/updateSocialAchievements'),
    updateTutorialAchievements: require('./achievements/updateTutorialAchievements')
}