module.exports = {
    registerUser: require('./registerUser'),
    authenticateUser: require('./authenticateUser'),
    retrieveUser: require('./retrieveUser'),
    retrievePosts: require('./retrievePosts'),
    retrievePosts: require('./retrievePosts'),
    retrievePost: require('./retrievePost'),
    updateUserPassword: require('./updateUserPassword'),
    updateUserAvatar: require('./updateUserAvatar'),
    createPost: require('./createPost'),
    deletePost: require('./deletePost'),
    updatePost: require('./updatePost'),
    updateUserEmail: require('./updateUserEmail'),
    toggleLikePost: require('./toggleLikePost'),
    retrieveLikedPosts: require('./retrieveLikedPosts'),
}