module.exports = {
  authenticateUserHandler: require('./authenticateUserHandler'),
  createCommentHandler: require('./createCommentHandler'),
  createPostHandler: require('./createPostHandler'),
  deleteCommentHandler: require('./deleteCommentHandler'),
  deletePostHandler: require('./deletePostHandler'),
  registerUserHandler: require('./registerUserHandler'),
  retrievePostHandler: require('./retrievePostHandler'),
  retrievePostsHandler: require('./retrievePostsHandler'),
  retrieveSavedPostsHandler: require('./retrieveSavedPostsHandler'),
  retrieveUserHandler: require('./retrieveUserHandler'),
  retrieveUserPostsHandler: require('./retrieveUserPostsHandler'),
  unsetPostPriceHandler: require('./unsetPostPriceHandler'),
  toggleLikePostHandler: require('./toggleLikePostHandler'),
  toggleSavePostHandler: require('./toggleSavePostHandler'),
  toggleVisibilityPostHandler: require('./toggleVisibilityPostHandler'),
  updatePostHandler: require('./updatePostHandler'),
  updateUserAvatarHandler: require('./updateUserAvatarHandler'),
  updateUserPasswordHandler: require('./updateUserPasswordHandler'),
}
