module.exports = {
  registerAdmin: require('./administrator/registerAdmin'),
  authenticateAdmin: require('./administrator/authenticateAdmin'),
  updateAdminEmail: require('./administrator/updateAdminEmail'),
  updateAdminPassword: require('./administrator/updateAdminPassword'),
  deleteAdmin: require('./administrator/deleteAdmin'),
  createUpdate: require('./update/createUpdate'),
  modifyUpdate: require('./update/modifyUpdate'),
  deleteUpdate: require('./update/deleteUpdate'),
  toggleUpdateVisibility: require('./update/toggleUpdateVisibility'),
  createEvent: require('./event/createEvent'),
  modifyEvent: require('./event/modifyEvent'),
  deleteEvent: require('./event/deleteEvent'),
  toggleEventVisibility: require('./event/toggleEventVisibility'),
  createLyricPost: require('./lyricPost/createLyricPost'),
  modifyLyricPost: require('./lyricPost/modifyLyricPost'),
  deleteLyricPost: require('./lyricPost/deleteLyricPost'),
  toggleLyricPostVisibility: require('./lyricPost/toggleLyricPostVisibility'),
  createMessage: require('./message/createMessage'),
  readMessage: require('./message/readMessage'),
  deleteMessage: require('./message/deleteMessage'),
  toggleMessageRead: require('./message/toggleMessageRead'),
  seeUpdate: require('./update/seeUpdate'),
  seeEvent: require('./event/seeEvent'),
  seeLyricPost: require('./lyricPost/seeLyricPost')
}