module.exports = {
    authenticateUserMid: require('./authenticateUserMid'),
    deleteUserMid: require('./deleteUserMid'),
    registerUserMid: require('./registerUserMid'),
    retrieveUserMid: require('./retrieveUserMid'),
    updateAvatarMid: require('./updateAvatarMid'),
    updateMailMid: require('./updateMailMid'),
    updateNameMid: require('./updateNameMid'),
    updatePasswordMid: require('./updatePasswordMid'),
    uploadPostMid: require('./uploadPostMid'),
    updatePostMid: require('./updatePostMid'),
    retrievePostMid: require('./retrievePostMid'),
    retrievePostsMid: require('./retrievePostsMid'),
    retrieveFavoritePostsMid: require('./retrieveFavoritePostsMid'),
    retrieveUserPostsMid: require('./retrieveUserPostsMid'),
    toggleFavMid: require('./toggleFavMid'),
    toggleLikeMid: require('./toggleLikeMid'),
    togglePublicStatMid: require('./togglePublicStatMid.js'),
    deletePostMid: require('./deletePostMid'),
}