module.exports = {
    registerUser: require('./registerUser'),
    authenticateUser: require('./authenticateUser'),
    getLoggedUser: require('./getLoggedUser'),
    updateCharacter: require('./updateCharacter'),
    updateUserEmail: require('./updateUserEmail'),
    updateUsername: require('./updateUsername'),
    updateUserPassword: require('./updateUserPassword'),
    deleteAccount: require('./deleteAccount'),
    createNewMission: require('./createNewMission'),
    retriveMissions: require('./retriveMissions'),
    retriveMission: require('./retriveMission'),
    updateMission: require('./updateMission'),
    deleteMission: require('./deleteMission'),
    updateUsername: require('./updateUsername'),
    updateUserEmail: require('./updateUserEmail'),
    updateUserPassword: require('./updateUserPassword'),
    createNewCharacter: require('./createNewCharacter'),
    getUserCharacter:require('./getUserCharacter'),
    registerCompletedMission: require('./registerCompletedMission'),
    retriveAdminMissions: require('./retriveAdminMissions')
}