module.exports = {
    authenticateUserHandler: require('./authenticateUserHandler'),
    deleteUserHandler: require('./deleteUserHandler'),
    registerUserHandler: require('./registerUserHandler'),
    retrieveUserHandler: require('./retrieveUserHandler'),
    updateAvatarHandler: require('./updateAvatarHandler'),
    updateMailHandler: require('./updateMailHandler'),
    updateNameHandler: require('./updateNameHandler'),
    updatePasswordHandler: require('./updatePasswordHandler'),
    uploadPostHandler: require('./uploadPostHandler'),
    updatePostHandler: require('./updatePostHandler'),
    retrievePostHandler: require('./retrievePostHandler'),
    retrievePostsHandler: require('./retrievePostsHandler'),
    retrieveFavoritePostsHandler: require('./retrieveFavoritePostsHandler'),
    retrieveUserPostsHandler: require('./retrieveUserPostsHandler'),
    toggleFavHandler: require('./toggleFavHandler'),
    toggleLikeHandler: require('./toggleLikeHandler'),
    togglePublicStatHandler: require('./togglePublicStatHandler.js'),
    deletePostHandler: require('./deletePostHandler'),
}